# Site settings
title:          Do Something.
description:    "The only source of knowledge is experience."
baseurl:        ""
url:            "https://nypark425.github.io"

# Author
author:
  name:         Zoe
  url:          https://nypark425.github.io
  email:        nypark425@gmail.com
  desc:         안녕하세요, 반가워요.

# Build settings
markdown:       kramdown

# Sass
sass:
  sass_dir:     _sass
  style:        compressed

# JS
js_dir:         /assets/js

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /post/:year-:month-:day/:title
paginate:       5
