# Site settings
title:          Stay with Joy.
description:    "The only source of knowledge is experience."
baseurl:        ""
url:            "https://staywithjoy.github.io"

# Author
author:
  name:         Joy
  namekr:       나연(Na-yeon)
  url:          https://staywithjoy.github.io
  email:        nypark425@gmail.com
  desc:         하루 하루의 즐거움이 모여 삶을 이룬다.

# Build settings
markdown:       kramdown

# Sass
sass:
  sass_dir:     _sass
  style:        compressed

# Static resources
js_dir:         /assets/js
img_dir:        /assets/image

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /post/:title
paginate:       5
