# Site settings
title:          Do Something.
description:    "The only source of knowledge is experience."
baseurl:        ""
url:            "https://dorongii.github.io"

# Author
author:
  name:         Zoe
  namekr:       나연(Na-yeon)
  url:          https://dorongii.github.io
  email:        nypark425@gmail.com
  desc:         안녕하세요, 하루하루의 행복을 추구하는 개발자입니다.

# Build settings
markdown:       kramdown

# Sass
sass:
  sass_dir:     _sass
  style:        compressed

# JS
js_dir:         /assets/js

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /post/:year-:month-:day/:title
paginate:       5
