# Site settings
title:          Do Something.
description:    "Do something what I want."
baseurl:        ""
url:            "https://nypark425.github.io"

# Author
author:
  name:         Amber
  url:          https://nypark425.github.io
  email:        nypark425@gmail.com
  desc:         안녕하세요, 관심분야가 두루두루 많은 개발자입니다.

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
